image: python:3.6.5

stages:
- build
- deploy

test:
    stage: build
    before_script:
    - pip install pipenv
    - make
    script:
    - make coverage

variables:
    DOCKER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

build:
    stage: build
    image: docker:latest
    services:
    - docker:dind
    before_script:
    - docker login registry.gitlab.com -u SolarLiner -p $REGISTRY_ACCESS_TOKEN
    script:
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE

deploy:
    stage: deploy
    image: node:latest
    variables:
        NOW_ALIAS: insaction-$CI_COMMIT_REF_SLUG
    before_script:
    - npm i -g now --silent --unsafe-perm
    - echo "FROM $DOCKER_IMAGE" > Dockerfile
    script:
    - NOW_URL=$(now --docker -t $NOW_TOKEN -n $NOW_ALIAS)
    - sleep 20
    - now alias $NOW_ALIAS
    - echo $NOW_ALIAS
    environment:
        name: $NOW_ALIAS
        url: https://$NOW_ALIAS.now.sh
    only:
    - master
    - staging
    - releases/*
    - hotfix/*

deploy_prod:
    stage: deploy
    image: node:latest
    variables:
        DOCKER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
        NOW_ALIAS: insaction
    before_script:
    - npm i -g now --silent --unsafe-perm
    - echo "FROM $DOCKER_IMAGE" > Dockerfile
    script:
    - NOW_URL=$(now --docker -t $NOW_TOKEN -n $NOW_ALIAS)
    - sleep 20
    - now alias $NOW_ALIAS
    environment:
        name: Production
        url: https://${NOW_ALIAS}.now.sh
    only:
    - release
    when: manual