image: python:3.6.5

before_script:
  - pip install pipenv
  - make
  
test:
  script:
    - make coverage
    
build-docker:
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login registry.gitlab.com -u SolarLiner -p $REGISTRY_ACCESS_TOKEN
  script:
    - docker build -t registry.gitlab.com/insaction-dev/main-website .
    - docker push registry.gitlab.com/insaction-dev/main-website
