language: python
python: '3.6'
cache: pip

install:
    - pip install pipenv
    - make
script:
    - make coverage
    - make cov-codacy
    
deploy-master:
    services:
        - docker
    sudo: required
    script:
        - docker build -t registry.gitlab.com/insaction-dev/main-website:master .
        - docker push registry.gitlab.com/insaction-dev/main-website:master
    only:
        branches:
            - master
            
deploy-release:
    services:
        - docker
    sudo: required
    script:
        - docker build -t registry.gitlab.com/insaction-dev/main-website:release .
        - docker push registry.gitlab.com/insaction-dev/main-website:release
    only:
        branches:
            - release
