language: python
python: '3.6'

install:
    - pip install pipenv
    - pipenv install
    - pipenv install --dev
script:
    - pipenv run coverage run --source='.' manage.py tests
    - pipenv run coverage xml
    - pipenv run python-codacy-coverage -r coverage.xml
