language: python
python: '3.6'
cache: pip
services:
- docker
sudo: required

jobs:
    include:
        - tests:
            script:
                - pip install pipenv
                - make
                - make coverage
                - make cov-codacy

        - deploy-master:
            script:
                - docker login $DOCKER_REGISTRY -u $DOCKER_USER -p $DOCKER_TOKEN
                - docker build -t registry.gitlab.com/insaction-dev/main-website:master .
                - docker push registry.gitlab.com/insaction-dev/main-website:master
            only:
                branches:
                    - master

        - deploy-release:
            script:
                - docker login $DOCKER_REGISTRY -u $DOCKER_USER -p $DOCKER_TOKEN
                - docker build -t registry.gitlab.com/insaction-dev/main-website:release .
                - docker push registry.gitlab.com/insaction-dev/main-website:release
            only:
                branches:
                    - release
