language: python
python: '3.6'
sudo: enabled

install:
    - pip install --user pipenv
    - pipenv install
    - pipenv install --dev
scripts:
    - pipenv run coverage run --source='.' manage.py tests
    - pipenv run coverage xml
    - pipenv run python-codacy-coverage -r coverage.xml
