language: python
python: '3.6'
cache: pip
services:
    - docker
sudo: required

install:
    - pip install pipenv
    - pipenv install --dev

jobs:
    include:
        - script: make coverage
        - script: make cov-codacy

        - stage: deploy
            script: docker login $DOCKER_REGISTRY -u $DOCKER_USER -p $DOCKER_TOKEN
        - script: docker build -t registry.gitlab.com/insaction-dev/main-website:master .
        - script: docker push registry.gitlab.com/insaction-dev/main-website:master
