# Generated by Django 2.0 on 2018-01-05 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='titre')),
                ('intro', models.TextField(max_length=350)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/articles')),
                ('contents', models.TextField(verbose_name='contenu')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='créé')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modifié')),
                ('views', models.IntegerField(default=0, verbose_name='vue')),
                ('slug', models.SlugField(unique=True)),
            ],
            managers=[
                ('articles', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True, verbose_name='nom')),
                ('description', models.TextField(max_length=350)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'catégorie',
            },
            managers=[
                ('categories', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headshot', models.ImageField(blank=True, null=True, upload_to='', verbose_name='photo de profil')),
                ('campus', models.CharField(choices=[('blois', 'Blois'), ('bourges', 'Bourges')], max_length=24)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'profil',
            },
            managers=[
                ('profiles', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Profile', verbose_name='auteur'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='catégorie'),
        ),
    ]
